import Head from 'next/head';
import Footer from '../components/Footer';
import Hero from '../components/Hero';
import NavBar from '../components/NavBar';
import Projects from '../components/Projects';
import Technologies from '../components/Technologies';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <NavBar />
      </section>
      <section>
        <Hero />
      </section>
      <section>
        <Projects />
      </section>
      <section>
        <Technologies />
      </section>
      <section>
        <Footer />
      </section>
    </div>
  );
}
